### ISSUE TITLE
Bug: Routing failure

### ISSUE THREAD

**Issue by coldKingdom** [iwyg/jitimage#16]
I'm trying to install the package in Laravel 4.1, but when I add the provider and alias and try to access the website I get

preg_match(): Numeric named subpatterns are not allowed

in /var/www/laravel.futuredev.se/laravel/vendor/laravel/framework/src/Illuminate/Routing/Matching/UriValidator.php on row 17 without even try to doing anything with the package.

When I disable the package by commenting the provider and alias for jitimage it works again.

Seems like a great package except the fact that I cannot try it, yet.. :)

**Comment by iwyg** [comment]
hm, that's pretty odd in deed.

**Comment by iwyg** [comment]
Seems like you have different version of 4.1 than me (preg_match being on line 19). 
Howerver it seems to be relate with `preg_match`. Could it possibly be related to this issue #5 (php 5.4.3)?

Edit: my be this will help you? https://github.com/laravel/framework/issues/2916

**Comment by coldKingdom** [comment]
I have only simple routes like

Route::get('admin/show/inbox/{id}', 'InboxController@show')->where('id', '[0-9]+');

Would that screw things up with the package enabled?

I have PHP 5.5.7 and no recipies, I don't get that far, sadly :(

**Comment by iwyg** [comment]
No, all I want to say is, that your laravel version might be buggy as mentioned here:  https://github.com/laravel/framework/issues/2916

**Comment by iwyg** [comment]
@coldKingdom Have you managed to get around this issue?

**Comment by coldKingdom** [comment]
@iwyg No, not yet.. I've been working on some other places, it seems like my Laravel has stopped updating for some reason. I will try to update it and get back to you with the results

**Comment by coldKingdom** [comment]
@iwyg Another package blocked the update to the latest Laravel. I had 4.1.0, now it's 4.1.13 and it's working..wohoo :)

**Comment by iwyg** [comment]
Glad to hear this :)
