### ISSUE TITLE
Im driver fails when filename contains spaces?

### ISSUE THREAD

**Issue by cviebrock** [iwyg/jitimage#17]
``` php
// path to file that exists
$path = '/uploads/path/to/my picture.jpg';

$jit = JitImage::source( $path )->cropAndResize(120,90,5);
```

Results in this error being thrown:

> ErrorException
> Command exited with 1: convert: unable to open image `/Users/cmv/Sites/petbucks/app/storage/uploads/path/to/my': No such file or directory @ error/blob.c/OpenBlob/2643. convert: unable to open image`picture.jpg': No such file or directory @ error/blob.c/OpenBlob/2643. convert: no images defined `jpeg:/private/var/tmp/jitim_Cpj4ZL' @ error/convert.c/ConvertImageCommand/3145. (View: /Users/cmv/Sites/test/show.blade.php)

Not sure if this is an imagick extension issue, or JitImage not escaping somewhere.  Any ideas?

**Comment by iwyg** [comment]
Confirmed. Applies to Imdriver. Is fixed now.
