### ISSUE TITLE
Jitimage won't work if source image path includes symlinks

### ISSUE THREAD

**Issue by cviebrock** [iwyg/jitimage#18]
Well, at least I think that's what's going on.  My app works just fine on my laptop, but when deploying using Rocketeer and shared folders, it doesn't.

My config has:

```
'base' => storage_path(),
```

In my case, that translates to:

```
/var/www/website/staging/releases/20140112015906/app/storage
```

This is a real directory.  Now, my image source is:

```
/uploads/pet/Flat-coated_Retriever_Molly2.jpg
```

However, the `uploads` dir is a symlink:

```
uploads -> /var/www/website/staging/shared/app/storage/uploads
```

So, the image that JitImage is looking for, and the real path to the file are, respectively:

```
/var/www/website/staging/releases/20140112015906/app/storage/uploads/pet/Flat-coated_Retriever_Molly2.jpg
/var/www/website/staging/shared/app/storage/uploads/pet/Flat-coated_Retriever_Molly2.jpg
```

If I pass in the first path, I get `null` returned from my calls to `JitImage::source( $src )->cropAndResize($w,$h,5);`.  If I pass in the actual path (without any symlinks in it), it works.

The culprit seems to be this method in JitImageResolver.php:

``` php
    public function getImageUrl(ImageInterface $image)
    {
        if (false !== ($strpos = strpos($image->getSource(), $this->config->base))) {
            $base = substr($image->getSource(), strlen($this->config->base));
            $input = $this->input;

            return sprintf(
                '/%s',
                trim(implode('/', [$this->config->base_route, $input['parameter'], trim($base, '/'),
                $input['filter']]), '/')
            );
        }
    }
```

In the conditional, the values of `$image->getSource()` and `$this->config->base` are, respectively:

```
/var/www/website/staging/shared/app/storage/uploads/pet/Flat-coated_Retriever_Molly2.jpg
/var/www/website/staging/releases/20140112015906/app/storage
```

So the condition fails, and the method returns `null`.

I can't solve this by wrapping all my paths in my config with `realpath()` (since the symlink is actually part of the file name, not the basepath), so I'm wondering if this can be done in the package ... ideally when it loads in the config, so that the `base` and `cache.path` values are translated.

Thanks!

**Comment by cviebrock** [comment]
Actually, I just realized that even if the package runs `realpath()` on the config values, it will fail because the symlink is part of the image path.  Thoughts?

**Comment by cviebrock** [comment]
Somewhat answering my own issue …

I updated my code so that the symlink portion of the path is part of base:

```
    'base' => storage_path('uploads'),
```

This solves basically everything **except** I now can only create JitImages from files within that base directory.  So, I can create thumbnails from uploaded images but, if a user doesn't upload an image, I can't create a thumbnail from something like `/public/img/default.png`.  I suppose I _could_ if I passed a URL instead of a path, but it would be nice if `JitImage::source()` would also accept an absolute path, instead of one just relative to the 'base'.

Is that possible?

**Comment by iwyg** [comment]
Not at the moment. I'm sorry. With regards to the symlinking problem, I assume there's a simple solution, but I have to look it up first and run some tests.

**Comment by iwyg** [comment]
One side note here. source() will accept absolute paths as long as you set base to the filesystem root '/'. The problem with that is. that Image URIs are becoming incredibly verbose.

**Comment by iwyg** [comment]
Seems like omitting the realpath conversion [here](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/JitImageResolver.php#L509) will solve the symlink issue.

**Comment by cviebrock** [comment]
Yeah, that would probably work.  I wasn't sure, though, why you had it there.

I've also found that I can get the results I want this way:

``` php
$src = JitImage::source('/relative/to/base/file.jpg')->cropAndResize(100,100);
$src = JitImage::source('file:///absolute/path/to/file.jpg')->cropAndResize(100,100);
```

**Comment by iwyg** [comment]
Yes, that's right. The resolver respects [file url schemes as it respects remote sources](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/JitImageResolver.php#L504).

**Comment by iwyg** [comment]
Can you confirm that 07b26f3 works for you?

**Comment by cviebrock** [comment]
That seems to have done it.  Thanks!
