### ISSUE TITLE
Actually define cache.prefix without underscores

### ISSUE THREAD

**Issue by cviebrock** [iwyg/jitimage#19]
The code here adds an underscore to the cached image URL:

https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/Cache/ImageCache.php#L121-L130

Can I suggest that the `sprintf()` string be changed from `'%s.%s_%s.%s` to `'%s.%s%s.%s` so that, if I don't want any underscore characters in my cached images, I won't get them?

This may seem like a minor point ... but Facebook, I believe, has trouble with images that contain underscores when using them for publishing to feeds (see http://stackoverflow.com/a/5572622/1327340 ).

**Comment by cviebrock** [comment]
Thank you!

**Comment by iwyg** [comment]
Now, if you need underscores, you have to set this on the cacheprefix ;)
