### ISSUE TITLE
Convert PDF to JPG?

### ISSUE THREAD

**Issue by ghost** [iwyg/jitimage#21]
Is this possible in any way with jitimage?

**Comment by iwyg** [comment]
Both imagemagick and imagick are capable of doing this, however this is not within the current scope of this library. In theory you could load your pdf like `file.pdf[0]` along with both, the im and imagick driver, and apply the convert filter. However, the filetypes are restricted to jpeg, gif, tif, and webp, so this would throw an exception.  

There're couple of php libraries that do handle pdf conversions. Just checkout [packagist.org](https://packagist.org/search/?q=pdf%20image)
