### ISSUE TITLE
Merging two images

### ISSUE THREAD

**Issue by abhimanyu003** [iwyg/jitimage#27]
Another feature I would like to suggest is of merging two images into one. Not complex but simple one, if you have two images you can merge second image on the top of other ( like watermark ) on any corner or centre of image. Or you can write text over image if you have font available.

**Comment by iwyg** [comment]
Write a custom filter :)

Intervention does a pretty good job on this stuff (although no imagick support afaik) http://intervention.olivervogel.net/image

And to be honest, I don't see any usecase where you would need just in time watermark creation.

**Comment by abhimanyu003** [comment]
I will give a try.
I know Intervention does this, main reason for using your library is because of `imagick` support.
With few minor addition your library will be perfect :)

**Comment by iwyg** [comment]
Closing this, you can write a custom filter to achieve such effects.
