### ISSUE TITLE
Unable to publish package

### ISSUE THREAD

**Issue by abhimanyu003** [iwyg/jitimage#28]
With the update of laravel v4.1.24 not able to publish package.
Error is

``` php
Missing argument 2 for Illuminate\Container\Container::Illuminate\Container\{closure}()
```

I'm not sure but seems error is with registering the package with the new update of laravel

**Comment by iwyg** [comment]
hm, would be odd if there's breaking change in the public api after a minor update. I'll have a look asap. Does this only happen when firing up artisan?

**Comment by abhimanyu003** [comment]
Yes this only happen when firing artisan command(s).

To test this
I run `composer update` by removing `post-update-cmd` from composer.json file.
Then manually trigger `php artisan clear-compiled` and same thing happen.

**Comment by iwyg** [comment]
No, it also happens when firing up laravel in general.  I've spotted the container binding that's causing this issue. However I think it's a bug on laravel's side.

**Comment by iwyg** [comment]
for reference: filed a bug [here](https://github.com/laravel/framework/issues/3906)

**Comment by iwyg** [comment]
temporary fix https://github.com/iwyg/jitimage/commit/709d94413e75730388605d0104c98a50a9af9757

**Comment by abhimanyu003** [comment]
Thanks a lot for fix, let see what Taylor reply on this
