### ISSUE TITLE
New recipes bug

### ISSUE THREAD

**Issue by n3m3s7s** [iwyg/jitimage#29]
First of all, thank You for your Work.
Today I've just updated my Laravel project from 4.1.23 to 4.1.24 and the package thapp/jitimage from dc0d286 to 709d944;

now when the 'recipes' array in the config file is not empty (so when I want to use Recipes) every script in the Project (even artisan commands) throws an ErrorException => "Missing argument 2 for Illuminate\Container\Container::Illuminate\Container{closure}";

the problem is the Jitimage package, if i disabled it from the config/app definition in Laravel everything just works fine; in order to avoid the throwing of the Exception I have to empty the "recipes" array, but my projects rely on Jitimage Recipes;
(before the last "composer update" everything worked as expected)

can You help me, please?!

Thanks you

**Comment by iwyg** [comment]
see #28

**Comment by n3m3s7s** [comment]
Thanks!
I'm sorry, but I've just tried to replace the "JitImageServiceProvider.php"
but the error is still throwed...
I have to wait for an upcoming update of Laravel framework in order to fix
this bug?

Thank you

2014-03-18 12:56 GMT+01:00 Thomas Appel notifications@github.com:

**Comment by iwyg** [comment]
see https://github.com/iwyg/jitimage/commit/709d94413e75730388605d0104c98a50a9af9757

remove both the service provider and the facade from conf/app.php. Select dev-master for the jitimage version in you composer.json and run a composer update.

**Comment by iwyg** [comment]
Oh wait

**Comment by iwyg** [comment]
There was another case (when using recipes) when the container would fail to resolve a service correctly. Should be working now.

**Comment by n3m3s7s** [comment]
Now it works!
Thank You very much!

2014-03-18 13:51 GMT+01:00 Thomas Appel notifications@github.com:
