### ISSUE TITLE
Question does this can cache image coming from external source?.

### ISSUE THREAD

**Issue by selif00** [iwyg/jitimage#30]
like im trying to cache image from the movie database and i get the full url to the image i would like to cache it and store in laravel cache system after image manipulation like.
1. external url source.
2. resize to fit parameter.
3. cache the image.
4. if cache avaliable get cache and serve.

**Comment by selif00** [comment]
also having problem installing the package

  Problem 1
    - Installation request for thapp/jitimage dev-master -> satisfiable by thapp/jitimage[dev-master].
    - symfony/symfony 2.5.x-dev requires symfony/icu ~1.0 -> no matching package found.
    - Conclusion: remove symfony/filesystem 2.5.x-dev
- thapp/jitimage dev-master requires symfony/filesystem 2.4.\* -> satisfiable by symfony/filesystem[2.4.x-dev, v2.4.0, v2.4.0-BETA1, v2.4.0-BETA2, v2.4.0-RC1, v2.4.1, v2.4.2].

**Comment by iwyg** [comment]
Remote sources are cached locally before being processed.

What Laravel version do you use?

**Comment by selif00** [comment]
Yes i manager to get it to work by forking and adding my repo and change the depend to 4.5 and now is installed and working. Now  i see that it in fact cache the image into the storage folder. i was wondering how can i retrieve the cache image i go into domain.com/jit/storage/{id} of couse replace the id with the id of the storage name dont know if the id is the folder or the file it self right now i call my images like this

thumbs/1/166/238/{{ $movies->url }}

but i think it recache it and i was trying to find out how can i call the storage cache image instead of the source again sorry but i cant find this anywhere in the documentation i would like to know something like

if image cache
them show cache image base on the img name ect
if no cache them cache and them call the cached image.

sorry my english is rusty im spanish and i believe im using laravel 4.1.*
maybe composer update to the new filesystem 4.5

**Comment by iwyg** [comment]
No worries.
the current laravel version (4.1.24) still uses the symfony 2.4.\* branch ([see here](https://github.com/laravel/framework/blob/v4.1.24/composer.json)), and so does jitimage. Once that'll change I update its dependancies. 

Once the image is cached and you have caching enabled in your `config.php` (caching is disabled unless your environment matches), a call to `thumbs/1/166/238/{{ $movies->url }}` will resolve to the path of the cached image. By default, you wouldn't be able to serve the image directly since the cache location is outside of the document root. 

Is there any use-case where you would need this?

**Comment by selif00** [comment]
i run a movie database website and im using the movie database api that when i get the movie info by the imdb id i get a json array with the image url for each movie. since i would like to locally cache the image to not hurt the api with to many request. thats what im trying to do.

**Comment by selif00** [comment]
if you want i can show you the site you can take a look but man since im started using your package the image speed up quite dramatically now it take way less to load the images. i wonder if is because the images already cached.here is the site http://glaisa.asosgaming.com/ you may need to register but is quick and fast.

**Comment by selif00** [comment]
i was using the other cache system call intervention it does work but tard slow and use only gd and i wanted to avoid using that and use im since is way faster than gd.

**Comment by iwyg** [comment]
As I said, once the remote image is cached it won't make any call the the remote source file again and instead uses the cached version (until you clear the cache, of course). The way it works is as follows (in short): 
- grab the source via curl and save it to /sys/tmp  
- process the tmp file
- cache it
- clear file from /sys/tmp

**Comment by selif00** [comment]
Ok sounds good seem faster than the other package i was using so Thumbs up to you. Great package. one more question. the cache stay forever until i clear the cache folder right?

**Comment by iwyg** [comment]
yes, however you can also clear the cache for only one image source. e.g. 

``` php
$app['jitimage.cache']->delete('uploads/images/myimage.jpg');
```

would only clear the cache for all processed files that derived from `uploads/images/myimage.jpg`

A general word of warning (and I should state this more clearly in the readme): **dynamic image processing** can easily kill your server. 

Imagine a bad guy calling a process route like `thumbs/2/200000000/2000000000/5/<somefile>` o_O. So better define recipes and trusted hosts in `config.php` and use the predefined routes instead.
