### ISSUE TITLE
Custom filters

### ISSUE THREAD

**Issue by stuba** [iwyg/jitimage#32]
Hi,

is there any more information about custom filters? I would like to create images with rounded edges and or cast shadows etc. I know these could be made with CSS, but it is unfortunately not supported by all (IE8-) browsers.

I could make pull request if somebody could just push me to a correct direction..

**Comment by iwyg** [comment]
What information in particular do you need?

In your case may be it's a start to look at how the Circ filters work https://github.com/iwyg/jitimage/tree/master/src/Thapp/JitImage/Filter/Circle
