### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jerauf** [iwyg/jitimage#33]
I'm getting an error when I try to install. Have tried 2 different servers.

This:

/vendor\/thapp\/jitimage\/src\/Thapp\/JitImage\/JitImageServiceProvider.php"

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"syntax error, unexpected '['","file":"\/nfs\/c06\/h04\/mnt\/123456\/domains\/domain.com\/vendor\/thapp\/jitimage\/src\/Thapp\/JitImage\/JitImageServiceProvider.php","line":68}}Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]  
  Error Output:       

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [packages1] ... [packagesN]

Has anyone else gotten this? How do you solve?

**Comment by iwyg** [comment]
you need php 5.4
