### ISSUE TITLE
Using trusted-sites

### ISSUE THREAD

**Issue by ghost** [iwyg/jitimage#39]
How can I use remote directory to deliver assets?

It is not described in the docs.

**Comment by iwyg** [comment]
[Coming version](https://github.com/iwyg/jitimage/tree/v0_2) adds support for aws/ftp/dropbox etc. via [flysystem](http://flysystem.thephpleague.com/) drivers, but for the current version you simply can't. 

However you can use sources that can be accessed via http (cURL), like `http://mysite.dev/images/2/200/200/5/http://media.25.tumblr.com/someimage.jpg`

**Comment by ghost** [comment]
Well I can't i get  NotFoundHttpException when I try to access remote file.

**Comment by iwyg** [comment]
Have you set the trusted sites? https://github.com/iwyg/jitimage#trusted-sites-array

Another reason may be that you don't have libcurl intsalled or the remote file really don't exists.

**Comment by iwyg** [comment]
is this solved now?

**Comment by ghost** [comment]
I have set the trusted sites and I have libcurl installed still it doesn't work. I get same exception when i try to apply some filter to an image only recipes are working.

Weeeeird.

**Comment by iwyg** [comment]
When using recipes, dynamic routes are disabled. https://github.com/iwyg/jitimage#predefined-image-processing.
