### ISSUE TITLE
[Proposal] Recipes and Dynamic Manipulation settings outside of config file

### ISSUE THREAD

**Issue by sniper7kills** [iwyg/jitimage#40]
It may already exist, but I didn't see any documentation on it.

What would be a nice feature is to be able to define recipes from the route file.

``` php
JitImage::addRecipe('recipeName','recipeSettings');
```

Or even just 

``` php
JitImage::disableDynamicManipulation()
```

At which point people could create routes similar to:

``` php
        Route::get('/thumbnail/{hash}', function()
    {
        return JitImage::source('path/to/'.$hash.'.jpg')->fit(200, 200);
    });
```

and not have to worry about people abusing JitImage

The main thing I'm looking for is a way to create recipe's without having to edit the config as I'm looking to use it from another package. And I don't think people using the package would want to create an install document stating how to configure another package.

Like I said these functions may already exist... and I may not have seen them yet.

**Comment by iwyg** [comment]
2nd point is almost already [there](https://github.com/iwyg/jitimage/blob/v0_2/Laravel/config/config.php#L45). I don't see the usefulness in point 1. 

Secondly, I consider the JitImage facade as a plain templating helper for blade (also see the [twig filters](https://github.com/iwyg/jitimage/tree/v0_2#twig) for comparison) . It just puts out URL's, so your routing example doesn't make much sense I guess.

BTW, you're always able to manipulate settings from another package in your service provider. In this case, you'll just have to [override](https://github.com/iwyg/jitimage/blob/master/src/Thapp/JitImage/JitImageServiceProvider.php#L279)`Thapp\JitImage\Controller\JitController` and set your own `RecipeResolver` instance, however, this will slightly change with the next version, as the resolver will be available on the IoC `jitimage.recipe_resolver`, so this should be even easier. You may vote for adding some `addRecipe` method to it, an I'll may consider this.

**Comment by iwyg** [comment]
Sorry, I forgot to mention that you'll also have to setup routes for your additional recipes.
