### ISSUE TITLE
 feature request: intergration with Amazon S3

### ISSUE THREAD

**Issue by akempes** [iwyg/jitimage#41]
It would be awesome if support for Amazon s3 could be integrated. 

I'm using S3 to store a large number of images because it's cheap. It would be great if the image key could be used to access the images in the S3 server. 
Maybe the cache files could be stored there as well...

Thanks for the already great package!

**Comment by iwyg** [comment]
Already there https://github.com/iwyg/jitimage/tree/v0_2 but still lacking documentation. Caching on remotes is also possible but very slow (~700 - 900ms). A bit faster, if the cache is accessible via http, but still slow ( ~ 250ms per image on dropbox).

**Comment by iwyg** [comment]
see #26
