### ISSUE TITLE
Re-sizing through chaining.

### ISSUE THREAD

**Issue by tomc3** [iwyg/jitimage#42]
It will be great if there is ability to chain though different image re-size.

Some time it required to crop a image first to a particular size and then re-size it.

Like 

``` php
JitImage::source('image')->cropAndResize(400, 225, 5)->cropAndResize(280, 280, 5);
```

**Comment by iwyg** [comment]
filter?

**Comment by tomc3** [comment]
Yes, we can use filters. But some how i'm not getting correct results. 

Not sure if it's my fault or not.
- Original Image: http://i.imgur.com/CbP2hYF.jpg ( Need to crop down black bars )
- Result after using below filter http://i.imgur.com/v2ceTsl.jpg

``` php
    public function run()
    {
        $image = $this->driver->getResource();
        $w = imagesx($this->driver->getResource());
        $h = imagesy($this->driver->getResource());
        $reSize = array('x' => 0 , 'y' => 45, 'width' => $w, 'height'=> 270);
        $thumb_im = imagecrop($image, $reSize);
        $this->driver->setOutputType('jpeg');
        $this->driver->swapResource($thumb_im);
    }
```
- Result after using `cropAndResize` on the above filtered image http://i.imgur.com/UySw6Ye.jpg

``` php
 JitImage::source('image.jpeg')->filter('mf')->cropAndResize(280, 280, 5);
```

Some how black bars appears again after using `cropAndResize`. It seems like processing is not taking place on the cropped image in step 2.

Filters are great, but some time they make task little harder to do. What I think chaining will be great in these type of situations. 

Filter is applied after, cropAndResize operation, is there any way it can be applied before that.

Thanks

**Comment by iwyg** [comment]
hm, GD, right? GD is sometimes (mostly) strange ;)

**Comment by iwyg** [comment]
I fear this is somewhat out of scope if what jitimage does, sorry

**Comment by tomc3** [comment]
Just found a other way around, double re-sizing. 
Not the best way but works perfectly.

``` php
        $thumbnail = JitImage::source('image.jpeg')->cropAndResize(350, 197, 5);
        preg_match('/storage\/(.*)(.+)(?=\.jpg)/', $thumbnail, $temp);
        $temp = str_replace('storage/', '', $temp);

        return JitImage::source('../app/storage/jit/' . $temp[0])->cropAndResize(374, 374, 5);
```
