### ISSUE TITLE
Gif to Jpeg

### ISSUE THREAD

**Issue by tomc3** [iwyg/jitimage#44]
Hello

`gif` is not getting converted to `jpeg` using driver `imagick`.

When you try to run this code.

``` php
return JitImage::source('uploads/iV5oWip2v.gif')->toJpeg()->cropAndResize(200, 200, 5);
```

The output is something like this.

``` php
http://site.dev:8000/test/storage/393a109f/testf0ce15d074e755feb1c.inode/x-empty
```

When you open the cache file, it's totally empty.

Hover-ever with GD is it is working fine.

Many thanks for your awesome package.

**Comment by iwyg** [comment]
you should probably add a filter that detects the gif source and replaces the resource with the first frame of the gif.

**Comment by tomc3** [comment]
Ok, I will try adding it.

What I think since this feature is inside the script, you must need to give a look at this. :)
