### ISSUE TITLE
How to delete cache (L5)

### ISSUE THREAD

**Issue by akempes** [iwyg/jitimage#50]
Hi,

I'm using the devlop branch for a new L5 project but I'm stuck with deleting cache files.
In L4 I always used:

``` php
$tmp = App::make('jitimage.cache');
$tmp->delete('test.jpg');
```

How does this work in L5?

Thanks!!

**Comment by iwyg** [comment]
You can use the [`CacheClearer`](https://github.com/iwyg/jitimage/blob/develop/Cache/CacheClearer.php), e.g.

``` php
<?php

$cl = $app->make('Thapp\JitImage\Cache\CacheClearer') ;
$cl->clear('images');
// or 
$cl->clearImage('images/myimage.jpg');
```

**Comment by iwyg** [comment]
sorry, should be:

``` php
<?php

$cl->clearImage('myimage.jpg', 'images');
```

**Comment by akempes** [comment]
Thanks!
