### ISSUE TITLE
Image not shown on Chrome/Safari

### ISSUE THREAD

**Issue by akempes** [iwyg/jitimage#51]
Hi,

I may found a bug ImageResponse prepare function. I found it hard to reproduce this error but I think it has something to do with the if-modified-since header. 
When this if statement is true, there is no image returned.

``` php
        if (($this->resource instanceof CachedResource || $this->resource->isFresh($time)) && $mod === $modDate) {
            $this->setHeadersIfNotProcessed($lastMod);
        } else {
            $this->setProcessedHeaders($this->resource, $lastMod);
        }
```

 I don't know exactly how it works, but in Chrome and Safari I noticed that some image ware 'sometimes' not loaded...

**Comment by iwyg** [comment]
Didn't come across this issue.

**Comment by akempes** [comment]
Please try to open this link in Chrome:
http://api.allianz.sector11.nl/images/thumb/cars/23/20150529022731_thumb-nissan-note-nismo-0005.jpg?v=1

The first visit will show a photo of a car. Now when I refresh this page I get a blank screen...
I hope you can now reproduce this issue...

**Comment by iwyg** [comment]
Hm, strange. I've noticed this couple of times on the php dev server. Maybe apache is affected, too. It Doesn't occur on nginx though.

**Comment by iwyg** [comment]
Hm, seems like the ImageResponse Object gets replaced within the AppKernel::handle() method.
